### ISSUE TITLE
`tldr` is already a popular cli tool for documentation

### ISSUE THREAD

**Issue by vosechu** [tendersearls/tldr#4]
https://tldr.sh/

I don't have a reasonable solution for you, but I wanted to make sure you knew while it was still relatively easy to change (if that's what you choose to do).

Feel free to close as "Won't Fix"!

Thank you for making it! I'm going to try to push this at my company. I might rename the binary though. :P

**Comment by searls** [comment]
Yes, we're aware. The gem ships with a `tldt` alias if you want to have both on your PATH https://github.com/tendersearls/tldr

**Comment by vosechu** [comment]
Oh perfect! Thank you!
